<div class="container-fluid marginBottomNosotros">
    <!-- <div class="row">
        <div class="col-md-12 paragraphGray">
            <img src="http://localhost/Php/coomulsap/public/img/Foto01.jpg" class="img-fluid" alt="">
        </div>
    </div> -->
    <div class="row">
        <div class="col-md-12">
            <div class="marginNosotros paragraphGray">
                <br/><h2 class="greenTitle">Nuestra historia</h2><br/>
                <p>En el año de 1988, el 20 de marzo, en el corregimiento de San Antonio de Prado, rincón montañoso ubicado al sur de Medellín, y hoy el corregimiento más poblado del país; un grupo de líderes comunitarios se reunió con el ánimo de constituir una “Cooperativa Especializada de Educación”. El registro y legalización se dio el 01 de Septiembre de 1988.<br/><br/>
                Durante estos primeros años la situación laboral era bastante complicada y el sacrificio que tenían que hacer los asociados era enorme, por lo que la mayoría no resistieron. En 1988 con tan solo 27 estudiantes se funcionaba precariamente en la escuela Carlos Betancur; también se funcionó en ésta sede en el año de 1989 con la asistencia final de 83 estudiantes. Para el año de 1990, se traslada al Idem San Antonio de Prado, con una matrícula inicial de 106 estudiantes. A pesar de que en 1991, en la misma planta física se pasó a 165 estudiantes, las dificultades fueron aumentando, ya que no se contaba con los recursos para pagar a los profesores y esto fue generando mala atmosfera entorno al proceso iniciado, pues algunos empleados del sector oficial tildaban a esta cooperativa de pirata. A esto se sumó el hecho de que los asociados que iniciaron se fueran retirando quedando tan solo catorce y de estos solo algunos cumplían con el pago de aportes sociales.<br/><br/>
                Como medida alternativa, decidieron transformar la Cooperativa Especializada de Educación, en Cooperativa Multiactiva de San Antonio de Prado, COOMULSAP. Se consideró que articulando otras actividades a la educación era una forma de poderla subsidiar.<br/><br/>
                Las medidas no sirvieron de mucho; los pocos asociados que quedaban habían perdido su entusiasmo. Sin el pago de los aportes pactados y recibiendo pocos ingresos por parte de los estudiantes; la situación se tornó inviable, por lo cual quienes componían los órganos de administración pensaron en liquidarla al iniciar el año de 1992.<br/><br/>
                Paralelamente otro grupo de personas lideradas por Ómar Cano Betancur, quienes integraban movimientos culturales para esta época, deseaban organizarse con el fin de solucionar problemas educativos en el corregimiento, pues muchos niños y jóvenes continuaban desescolarizados, pero no tenían con que pagar por el servicio. Estos fines eran similares a los de COOMULSAP; con la diferencia de que quienes iniciaron el proceso le cobraban a las estudiantes, mientras que el grupo que llegaba consideraba que el pago era una obligación del estado, y era necesario buscar la forma de que se cumpliera con dicho fin. En este sentido no se dio la liquidación sino que se generó un relevo natural entre los iniciadores del proceso y el grupo cultural deseoso de transformar a prado a través de la educación.<br/><br/>
                En este año, 1992, uno de los nuevos asociados, Rodrigo Garcés, facilitó una finca (Yuruparí); la cual fue precariamente adecuada y sería la primera sede no oficial de COOMULSAP.<br/><br/>
                En 1995 se hicieron las gestiones necesarias con el fin de obtener una planta física que construyó la urbanización compartir como compensación urbanística y que sería entregada al municipio de Medellín. La gestión fue exitosa y al año siguiente el colegio Cooperativo tendría una sede óptima para prestar el servicio educativo a la comunidad pradeña. Se abandona así la finca Yuruparí y se da el traslado hacia la urbanización compartir.<br/><br/>
                En 1996 a pesar del entusiasmo con el que habían comenzado los nuevos asociados y de las becas gestionadas, como las becas PACES, y posteriormente con el municipio de Medellín (gracias a la nueva sede obtenida), la situación no era sencilla; el pago por parte de los entes estatales no era puntual y no alcanzaba a subsidiar la totalidad del costo por estudiante. En 1997 las pérdidas ascendieron a veinticuatro millones de pesos.<br/><br/>
                En 1998 se estaba fortaleciendo cada vez más la educación contratada en el municipio de Medellín y el departamento de Antioquia.<br/><br/>
                Hasta este momento, además del Colegio Compartir, le habían sido adjudicadas a COOMULSAP las siguientes instituciones: Colegio La Pastora en Buenos Aires; Héctor Higinio Bedoya, de Pueblito; Escuela La Pava, de Heliconia; Escuela Ventanitas, en el Limonar; Escuela San Nicolás, en Aranjuez; y posteriormente la escuela Pradito, en San Antonio de Prado.<br/><br/>
                En 1999 orientados por Pro-Antioquia, el Centro de Ciencia y Tecnologías de Antioquia (CTA) y La Fundación Corona; se inicia un proceso de reflexión, tanto educativa como administrativa y el cual duraría hasta el año 2002. De este proceso fueron activos protagonistas: Fernando Cano Betancur (docente del Colegio Cooperativo) Gustavo Jaramillo Franco (director de la Escuela San Nicolás), Alba Lucia Vahos (directora Colegio La Pastora), Héctor Olarte González (rector Colegio Cooperativo) y Ramón Echavarría Patiño (coordinador de disciplina Colegio Cooperativo). La tesis sostenida por las entidades antes descritas, era que la clave en el mejoramiento de la calidad de la educación estaba la estandarización de los procesos administrativos; sin embargo, el grupo de COOMULSAP, apoyados inicialmente por Ernesto García Posada, sostenían que además de esto, era eje fundamental de la transformación educativa la reflexión pedagógica permanente por parte de docentes y directivos.<br/><br/>
                COOMULSAP, a pesar de que inició estos procesos de reflexión y mejoramiento, fue perdiendo las instituciones que le habían sido entregadas frente a otras entidades, igualmente sin ánimo de lucro. En el año 2001 se pierde además el Colegio La Pastora. De esta forma para este momento tan solo se contaba con las sedes Compartir y San Nicolás, y un total de 1400 estudiantes.<br/><br/>
                Se pensó en incursionar en otros frentes, por lo que la línea de producción, parecía atractiva. Esto teniendo en cuenta la problemática que vivían los productores de leche de San Antonio de Prado. Se crea así una planta de lácteos en una finca de uno de sus asociados.<br/><br/>
                De esta forma para el año 2002, la principal amenaza que presentaba COOMULSAP era la de no contar con una planta física propia. Por mucho que se avanzara en la reflexión pedagógica difícilmente se lograría una transformación social sino se contaba con espacios educativos para hacerlo y comunidades en donde hacer presencia. La dinámica mostraba que las plantas físicas públicas eran solicitadas fácilmente y en cualquier momento.<br/><br/>
                Teniendo como antecedente la reflexión hecha durante cuatro años en asuntos administrativos y educativos, sumado a la experiencia ya recorrida, con un claro conocimiento sobre los errores cometidos, y sintiendo que era fundamental consolidar procesos desde el punto de vista ideológico; se decide reorientar los horizontes de COOMULSAP.    <br/><br/>
                Como primera medida se toma la decisión de hacer relevo en la gerencia, por lo cual se nombra al Licenciado Gustavo Jaramillo Franco, quien había participado de todo el proceso de reflexión con las entidades antes descritas; a su vez se decide construir una planta física propia que permitiera la continuidad de los procesos y la aplicación de las herramientas administrativas y la reflexión educativa. Con muy pocos recursos y gracias a un préstamo se adquiere un lote y se inicia en el año 2003 los trámites ante la curaduría.<br/><br/>
                En 2006 ya construido el 60% de la planta física se crea lo que hoy es el Colegio Empresarial. Este proceso fue paralelo a la construcción de los colegios de calidad del municipio de Medellín; colegios que continuarían la línea donde la administración prima sobre la pedagogía.<br/><br/>
                A partir de este año se fortalecen los procesos investigativos y académicos con los estudiantes. Se inicia el proceso de educación inicial, a través del programa Buen Comienzo del municipio de Medellín; y se tramitan las licencias para poder impartir la educación de adultos. A su vez y procurando impactar la comuna uno de la ciudad, se adquiere una pequeña casa y se instaura allí una sede del Colegio Cooperativo, denominada Fray Luis Amigo.<br/><br/>
                A partir del año 2008 se fue consolidando mucho más lo que es hoy una educación de excelente calidad, pues trabajando en el marco de “Medellín la más educada” (programa bandera de la administración municipal 2008-2011, y con la cual se gozó de un excelente apoyo); y en el marco de los diversos eventos que resaltaban la educación, comenzó a visualizarse mucho más la gestión de las dos instituciones creadas y administradas por COOMULSAP; el Colegio Cooperativo y el Colegio Empresarial.<br/><br/>
                En el año 2009, pensando en alternativas que desembocaran en una educación útil para el medio, se crea la institución para el trabajo y el desarrollo humano CEMCO (Centro de Estudios Empresariales de Coomulsap).<br/><br/>
                A su vez se adquiere una finca en la vereda El Vergel, con el fin de implementar allí una sede de educación inicial, bajo el programa Buen Comienzo.<br/><br/>
                En el año 2010 se decide llegar a sectores alejados del país, por lo que a través de la política de Primera Infancia del Gobierno Nacional, se inició la prestación del servicio en los municipios de Primavera y Puerto Carreño, en el Vichada y Mitú en Vaupés.<br/><br/>
                En este mismo año en cabeza de su gerente se presentan los postulados de la Pedagogía de la Acción Solidaria, la cual “esta cimentada en la cooperación como acción fundamental para el con-vivir y en la solidaridad como principio universal que permite un encuentro con el otro en un mundo de desidia, falencias e incertidumbres”.<br/><br/>
                En el año 2011 se crea la planta de alimentos “Aldea Solidaria”, ubicando su sede principal en el barrio Sevilla, con sedes alternas en Guayabal y San Antonio de Prado.<br/><br/>
                A su vez en este mismo año bajo un convenio de asociación, con un significativo aporte por parte de COOMULSAP, se comienza la administración de uno de los jardines de calidad del municipio de Medellín, construido en el barrio El Limonar de San Antonio de Prado.<br/><br/>
                Paralelamente en el año 2011 es presentada en el Congreso Iberoamericano de Pedagogía en Cartagena, la propuesta pedagógica de COOMULSAP, la “Pedagogía de la Acción Solidaria”.<br/><br/>
                En el año 2012 se compra un lote y se inicia la construcción del Jardín Infantil Horizontes, la cual podrá a su vez ser la sede principal del Colegio Cooperativo, licencia que fue concedida al finalizar dicho año.<br/><br/>
                En este año en el marco de la estrategia de “Cero a Siempre”, política de primera infancia del Gobierno Nacional 2011-2015 su gerente es nombrado como representante a nivel nacional en la comisión de seguimiento a dicha estrategia en representación de todas las organizaciones del país.<br/><br/>
                En el año 2013 se comienza a prestar el servicio en el Barrio El Limonar, en San Antonio de prado, Colegio Corvide. De igual forma a través del ICBF se inicia la prestación del servicio en el municipio de San Roque.<br/><br/>
                Entre muchos otros se pueden resaltar los siguientes logros:<br/>
                </p>
                <ul class="list-group">
                    <li class="list-group-item">Cuarto lugar entre 56 países en Reno Nevada, Estados unidos en la Feria Intel de Tecnología, 2009;</li>
                    <li class="list-group-item">Premio a Experiencia significativa Medellín la más educada, al Colegio Cooperativo por los procesos investigativos en el año 2009;</li>
                    <li class="list-group-item">Primer lugar Feria Explora año 2010 con lo cual dos niños de la comuna uno viajan la NASA, Houston, Texas;</li>
                    <li class="list-group-item">Medalla al Mérito Concejo de Medellín por el trabajo con la población vulnerable de la ciudad, sede San Cayetano.</li>
                    <li class="list-group-item">En el año 2011 los dos colegios, COOPERATIVO Y EMPRESARIAL, son nominados por el premio Medellín la más educada, a mejor colegio de calidad de la ciudad de Medellín, categoría público. Teniendo en cuenta el mayor tiempo en los procesos, gana el premio el Colegio COOPERATIVO.</li>
                    <li class="list-group-item">Este mismo año (2011) se hace mención de honor a una docente por el liderazgo en la ciudad en los procesos investigativos.</li>
                    <li class="list-group-item">Con el Colegio Empresarial, año 2012 se logra el premio a experiencia significativa por la “Estadística como elemento fundamental en los procesos de aprendizaje”; y reconocimiento a un docente del Colegio Cooperativo por su trabajo en las TICS.</li>
                    <li class="list-group-item">Al finalizar el mismo año el Colegio Empresarial se ubica como el mejor colegio de educación pública gratuita de la ciudad de Medellín, según los resultados ICFES SABER 11, nivel muy superior y top 100 de los mejores colegios de Antioquia.</li>
                    <li class="list-group-item">En Noviembre de 2013 le es entregado al Colegio Empresarial el Premio Medellín un hogar para la vida, como el mejor colegio público de la ciudad; a su vez el Colegio Cooperativo gana el premio a experiencia significativa por el simposio corregimental de recursos naturales y medio ambiente.</li>
                </ul>
                <p>Luego de haber mostrado excelentes resultados en la ciudad de Medellín, tanto en administración como en los procesos educativos, las amenazas no terminan, pero nuestros deseos de seguir trabajando por la sociedad no flaquean. Con la solidaridad y la cooperación como banderas continuaremos aportando a la educación de los más de diez mil niños, jóvenes y adultos, que hoy atendemos en la ciudad de Medellín y el departamento de Antioquia. No somos privatizadores, somos sector solidario; unos convencidos de que la sociedad pueda transformarse a partir de una educación gratuita, integral, incluyente y al servicio de las personas.</p>
            </div>
        </div>
    </div>
</div>
